#!/bin/sh

set -x

if [ "$VARNISH_CANONICAL_HOST" = "default" ]; then
  VARNISH_CANONICAL_HOST=""
fi

cat<< __EOF__ >/etc/default/varnish
# Should we start varnishd at boot?  Set to "no" to disable.
START=yes

# Maximum number of open files (for ulimit -n)
NFILES=131072

# Maximum locked memory size (for ulimit -l)
# Used for locking the shared memory log in memory.  If you increase log size,
# you need to increase this number as well
MEMLOCK=82000

# Unknown parameter "sess_timeout"
#          -p sess_timeout=${VARNISH_SESS_TIMEOUT} \\

DAEMON_OPTS="-a :6081 \\
              -u varnish \\
              -P /var/run/varnishd.pid \\
              -a :80 \\
              -T :6082 \\
              -f /etc/varnish/default.vcl \\
              -S /etc/varnish/secret \\
              -p thread_pool_min=${VARNISH_THREAD_POOL_MIN} \\
              -p thread_pools=${VARNISH_THREAD_POOLS} \\
              -p cli_timeout=${VARNISH_CLI_TIMEOUT} \\
              -s file,/var/lib/varnish/varnish_storage.bin,${VARNISH_STORAGE}"

__EOF__


/usr/bin/m4 -DVARNISH_NAME="[[$VARNISH_NAME]]" \
                -DVARNISH_CANONICAL_HOST="[[$VARNISH_CANONICAL_HOST]]" \
                -DVARNISH_BACKEND_HOST="[[$VARNISH_BACKEND_HOST]]" \
                -DVARNISH_BACKEND_PORT="[[$VARNISH_BACKEND_PORT]]" \
                -DVARNISH_BACKEND_CONNECT_TIMEOUT="[[$VARNISH_BACKEND_CONNECT_TIMEOUT]]" \
                -DVARNISH_BACKEND_FIRST_BYTE_TIMEOUT="[[$VARNISH_BACKEND_FIRST_BYTE_TIMEOUT]]" \
                -DVARNISH_BACKEND_BETWEEN_BYTES_TIMEOUT="[[$VARNISH_BACKEND_BETWEEN_BYTES_TIMEOUT]]" \
                -DVARNISH_PROBE_REQUEST="[[$VARNISH_PROBE_REQUEST]]" \
                -DVARNISH_PROBE_HOST="[[$VARNISH_PROBE_HOST]]" \
                -DVARNISH_PROBE_WINDOW="[[$VARNISH_PROBE_WINDOW]]" \
                -DVARNISH_PROBE_THRESHOLD="[[$VARNISH_PROBE_THRESHOLD]]" \
                -DVARNISH_PROBE_INTERVAL="[[$VARNISH_PROBE_INTERVAL]]" \
                -DVARNISH_PROBE_TIMEOUT="[[$VARNISH_PROBE_TIMEOUT]]" \
                -DVARNISH_GRACE_HEALTHY="[[$VARNISH_GRACE_HEALTHY]]" \
                -DVARNISH_GRACE_UNHEALTHY="[[$VARNISH_GRACE_UNHEALTHY]]" \
                -DVARNISH_TTL_CONTENT="[[$VARNISH_TTL_CONTENT]]" \
                -DVARNISH_TTL_ASSETS="[[$VARNISH_TTL_ASSETS]]" \
                  /etc/varnish/$VARNISH_CONFIG_TEMPLATE > /etc/confd/templates/varnish.vcl.tmpl

service varnish start

/usr/bin/confd -prefix=$CONFD_PREFIX -interval=$CONFD_INTERVAL -node=http://$ETCD_HOST:$ETCD_PORT 

service varnish stop

